// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkDCOU0bIg9-GOeeFSvsq5orrnkjzz3s',
    appId: '1:782990163085:web:a31458c8c5d8ed83c636c4',
    messagingSenderId: '782990163085',
    projectId: 'trailguard-ai',
    authDomain: 'trailguard-ai.firebaseapp.com',
    storageBucket: 'trailguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtAeQlgtanW-JAT68KPbucRzQGFfC9S4',
    appId: '1:782990163085:android:b0299f1c0bced1cbc636c4',
    messagingSenderId: '782990163085',
    projectId: 'trailguard-ai',
    storageBucket: 'trailguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkDCOU0bIg9-GOeeFSvsq5orrnkjzz3s',
    appId: '1:782990163085:web:5ead2f1d3e7be875c636c4',
    messagingSenderId: '782990163085',
    projectId: 'trailguard-ai',
    authDomain: 'trailguard-ai.firebaseapp.com',
    storageBucket: 'trailguard-ai.firebasestorage.app',
  );
}










